### ISSUE TITLE
[🐛] App fetches `ephemeral` folder projects too

### ISSUE THREAD

**Issue by yahu1031** [FlutterMatic/desktop#63] opened 2022-02-15 20:15 UTC
**Describe the bug**
I set the path of the projects in settings and refreshed the projects tab. then I get all the `ephemeral` folder projects to the screen.

**To Reproduce**
1. Go to settings
2. Click on projects
3. Add the projects folder
4. Close settings and refresh the projects tab.

**Expected behavior**
Should only fetch the projects not the dependencies folders too.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/154141535-528f7d8a-1814-4aaf-8b4d-9ec19553f76f.png)

**Desktop:**
 - OS: Windows

**Logs:**
[fm_report_2022-2-16-1-40-21.log](https://github.com/FlutterMatic/desktop/files/8074335/fm_report_2022-2-16-1-40-21.log)

**Comment by ZiyadF296** [comment] 2022-02-15 20:23
This is pending to be fixed and fix is simple.

**Comment by yahu1031** [comment] 2022-02-15 20:28
This isn't an enhancement I guess. Cause this feature is existing and it has bugs.

**Comment by ZiyadF296** [comment] 2022-02-16 04:29
It is an enhancement. It is an existing feature that can be improved.

**Comment by ZiyadF296** [comment] 2022-02-16 18:51
Solved with no option to avoid. Will add this option if enough people upvote this.

**Comment by ZiyadF296** [comment] 2022-02-17 05:40
@yahu1031 please confirm that the feature works as intended. If yes then please close this issue.

**Comment by yahu1031** [comment] 2022-02-17 05:53
Will check this and confirm.

**Comment by ZiyadF296** [comment] 2022-02-24 19:35
If this issue persists, please file a new issue.

**Closed** 2022-02-24 19:35 UTC
Labels: enhancement, p3
